// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLN_r6HEVU0qboih-98P4MlD7QbHAGFw0',
    appId: '1:963721562453:web:2854eb822c6779d2dec7dc',
    messagingSenderId: '963721562453',
    projectId: 'beinfluencer-41738',
    authDomain: 'beinfluencer-41738.firebaseapp.com',
    storageBucket: 'beinfluencer-41738.appspot.com',
    measurementId: 'G-008ZV9KRMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJJJfmIfn7UYmWVUZP8qtwea-I3OMcFY',
    appId: '1:963721562453:android:45ecec7fac71031adec7dc',
    messagingSenderId: '963721562453',
    projectId: 'beinfluencer-41738',
    storageBucket: 'beinfluencer-41738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLt54-NXXR2zdSdYS0arK4vsiax8WZfg',
    appId: '1:963721562453:ios:d9643fc930dde4a0dec7dc',
    messagingSenderId: '963721562453',
    projectId: 'beinfluencer-41738',
    storageBucket: 'beinfluencer-41738.appspot.com',
    iosBundleId: 'com.azhana.beinfluencer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkLt54-NXXR2zdSdYS0arK4vsiax8WZfg',
    appId: '1:963721562453:ios:0edd3a4320b0344edec7dc',
    messagingSenderId: '963721562453',
    projectId: 'beinfluencer-41738',
    storageBucket: 'beinfluencer-41738.appspot.com',
    iosBundleId: 'com.example.influApp.RunnerTests',
  );
}
